name: Create PR from Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge changes from develop to main"
          branch: main
          title: "Merge changes from develop to main"
          body: "This pull request automatically merges changes from the develop branch to the main branch."
          draft: true
