# File: .github/workflows/pull-request.yml

name: Create Pull Request

on:
  push:
    branches:
      - develop

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Create Pull Request
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO_API_URL=$(jq -r .repository.url $GITHUB_EVENT_PATH)
          PR_TITLE="Merge develop into main"
          PR_BODY="This is an automated pull request to merge changes from develop into main."

          curl -X POST "$REPO_API_URL/pulls" \
            -H "Authorization: token $TOKEN" \
            -d '{
              "title": "'"$PR_TITLE"'",
              "body": "'"$PR_BODY"'",
              "head": "develop",
              "base": "main"
            }'
