# File: .github/workflows/pull-request.yml

on:
  push:
    branches:
      - develop

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Merge develop into main"
          labels: "automated"
          branch: "main"
          base: "main"
          body: |
            This is an automated pull request to merge changes from develop into main.
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PR URL
        run: echo "Pull Request URL - ${{ steps.create_pr.outputs.pull-request-url }}"
