# File: .github/workflows/pull-request.yml

on:
  push:
    branches:
      - develop

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Pull Request para main
          title: "Pull Request para main"
          branch: develop # The branch where the PR will be created
          base: main # The branch you want to merge into
          labels: |
            automated pr
