name: Create Pull Request

on:
  push:
    branches:
      - develop

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with GitHub token
        id: auth
        uses: octokit/auth-action@v2.x
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/pulls
          token: ${{ steps.auth.outputs.token }}
          body: |
            {
              "title": "Merge develop into main",
              "head": "develop",
              "base": "main",
              "body": "This is an automated pull request to merge changes from develop into main."
            }
