name: Create PR from Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create branch
        run: git checkout -b pr-branch

      - name: Create Pull Request
        id: create_pr
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO="${{ github.repository }}"
          TITLE="Merge changes from develop to main"
          BODY="This pull request automatically merges changes from the develop branch to the main branch."
          URL="https://api.github.com/repos/$REPO/pulls"
          BASE="main"
          HEAD="pr-branch"
          RESPONSE=$(curl -X POST -s -H "Authorization: token $TOKEN" -d "{\"title\":\"$TITLE\",\"body\":\"$BODY\",\"head\":\"$HEAD\",\"base\":\"$BASE\"}" "$URL")
          echo "$RESPONSE"
          PR_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          echo "::set-output name=url::$PR_URL"

      - name: PR URL
        run: echo "The pull request URL is ${{ steps.create_pr.outputs.url }}"
